// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/inoth/cronsvc/internal/controller"
	"github.com/inoth/cronsvc/internal/server"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
	"github.com/inoth/toybox/ginsvr"
)

// Injectors from wire.go:

func initApp(cfg config.CfgBasic) *toybox.ToyBox {
	configMate := config.NewConfig(cfg)
	taskController := controller.NewTaskController()
	ginHttpServer := server.NewHttpGinServer(taskController)
	toyBox := newApp(configMate, ginHttpServer)
	return toyBox
}

// wire.go:

func newApp(
	conf config.ConfigMate,
	hs *ginsvr.GinHttpServer,
) *toybox.ToyBox {
	t := toybox.New(toybox.WithConfig(conf), toybox.WithServer(hs))
	return t
}
